[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:sshd]
command=/usr/sbin/sshd -D
autostart=true
autorestart=true
priority=10

[program:init_mysqld]
command=/usr/local/bin/init_mysql.sh
user=root
autostart=true
autorestart=false
priority=20
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:mysqld]
command=/usr/sbin/mysqld
user=mysql
autostart=true
autorestart=true
priority=30
startsecs=30
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:watch_mysql_log]
command=/usr/local/bin/watch_mysql_log.sh
user=root
autostart=true
autorestart=true
priority=40
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

# [program:1panel]
# command=/usr/local/bin/start_1panel.sh
# autostart=true
# autorestart=true
# startsecs=10
# startretries=3
# stdout_logfile=/dev/null
# stdout_logfile_maxbytes=0
# stderr_logfile=/dev/null
# stderr_logfile_maxbytes=0

[program:gemini-balance]
command=/usr/local/bin/start_gemini_balance.sh
autostart=true
autorestart=true
user=root
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=50